# Generated by Django 4.0.3 on 2022-04-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermod', '0003_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default=4970, max_length=6),
        ),
    ]
